name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12

    name: Build
    steps:
    - uses: actions/checkout@v3
    #- name: Build
    #  run: xcodebuild -scheme ContributionGraph -project ContributionGraph.xcodeproj
    - name: Run unit tests
      run: xcodebuild test -scheme ContributionGraph -project ContributionGraph.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.5' -enableCodeCoverage YES | xcpretty
    - name: Swift Coverage Conversion
      uses: sersoft-gmbh/swift-coverage-action@v3
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
