name: unit_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_unit_tests:
    runs-on: macos-12

    name: unit_test iOS
    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: xcodebuild test -scheme ContributionGraph -project ContributionGraph.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.5'
