name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    
    env:
      XCODEBUILD_TEST_DEST: "platform=iOS Simulator,name=iPhone 11,OS=15.5"
      XCODEBUILD_TEST_ARGS: "-scheme ContributionGraph -project ContributionGraph.xcodeproj -enableCodeCoverage YES"  

    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Run UI tests
      run: xcodebuild test $XCODEBUILD_TEST_ARGS -destination '$XCODEBUILD_TEST_DEST' -only-testing:ContributionGraphUITests | xcpretty    
    - name: Run Unit tests
      run: xcodebuild test-without-building $XCODEBUILD_TEST_ARGS -destination '$XCODEBUILD_TEST_DEST' -only-testing:ContributionGraphTests | xcpretty
    - name: Swift Coverage Conversion
      uses: sersoft-gmbh/swift-coverage-action@v3
      with:
        target-name-filter: ^ContributionGraphTests$
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
