name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  XCODE_DERIVED_DATA: ~/Library/Developer/Xcode/DerivedData/ContributionGraph-*/Build
  APP_NAME: ContributionGraph

jobs:
  build:
    runs-on: macos-12
    
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: xcodebuild test -scheme ContributionGraph -project ContributionGraph.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.5' | xcpretty
    - name: Swift Coverage Conversion
      run: xcrun llvm-cov export -format=lcov -instr-profile=$XCODE_DERIVED_DATA/ProfileData/*/Coverage.profdata $XCODE_DERIVED_DATA/Products/Debug-iphonesimulator/$APP_NAME.app/APP_NAME > coverage.lcov
    #  uses: sersoft-gmbh/swift-coverage-action@v3
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
